"""empty message

Revision ID: 46f28a4d7324
Revises: 50dbb66cc6ce
Create Date: 2017-04-10 08:02:47.690471

"""

# revision identifiers, used by Alembic.
revision = '46f28a4d7324'
down_revision = '50dbb66cc6ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
