"""empty message

Revision ID: 50dbb66cc6ce
Revises: 80c5371753d
Create Date: 2017-04-10 07:56:34.011159

"""

# revision identifiers, used by Alembic.
revision = '50dbb66cc6ce'
down_revision = '80c5371753d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
