"""empty message

Revision ID: 80c5371753d
Revises: 32082369fa67
Create Date: 2017-04-10 04:38:34.845277

"""

# revision identifiers, used by Alembic.
revision = '80c5371753d'
down_revision = '32082369fa67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
